### ISSUE TITLE
Add GitHub action for PDF generation 

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs-antora#10]
## Background
We need specifications in PDF format to review them. 

## Task
- Add a GitHub action to generate PDFs from AsciiDoc specifications. 
This action should be configured for manual triggers on GitHub. 
After the trigger, PDFs should be generated for all specifications managed in the aas-specs-antora repository.

- In addition, please include documentation in the README.md file describing the steps to manually trigger this action and download the generated PDF documents.

**Comment by monsieuremre** [comment]
Done in completion. I made it tie to the regular process, and pdf files are upload as well. So every 6 hours, pdf files are also generated and uploaded. You can track them in the following links. Updated the readme file with the necessary clarification. The theme is also applied.

* [Main Page](https://rwth-iat.github.io/aas-specs-antora/index/dev/the-asset-administration-shell-specification.pdf)

* [Part 1](https://rwth-iat.github.io/aas-specs-antora/IDTA-01001/snapshot/draft-part-1-metamodel.pdf)

* [Part 2](https://rwth-iat.github.io/aas-specs-antora/IDTA-01002-3/snapshot/draft-part-2-api.pdf)

* [Part 3a](https://rwth-iat.github.io/aas-specs-antora/IDTA-01003-a/snapshot/draft-specification-asset-administration-shell-part-3a-iec61360.pdf)

* [Part 5](https://rwth-iat.github.io/aas-specs-antora/IDTA-01005/snapshot/draft-specification-asset-administration-shell-part-5-aasx-package-format.pdf)

**Comment by zrgt** [comment]
Great, thank you! Is it possible to add a button for downloading PDF in ui? E.g. some download Button near "snapshot"?

**Comment by zrgt** [comment]
> There is a problem with the cover page, which is expected. We should look into not having the cover page as an image and having it be a proper real pdf cover page that is made of formatted text. Image cover pages create complications because they don't always have the same name accross diffferent files.

Can you please an issue for cover image in this repository and assign it to me. I will discuss the problem with idta

**Comment by zrgt** [comment]
> There is a problem with the cover page, which is expected. We should look into not having the cover page as an image and having it be a proper real pdf cover page that is made of formatted text. Image cover pages create complications because they don't always have the same name accross diffferent files.

I guess it is not a good idea to reference these links in Readme.md, as we will have to update it, if new docs appear

**Comment by monsieuremre** [comment]
> Great, thank you! Is it possible to add a button for downloading PDF in ui? E.g. some download Button near "snapshot"?

I have also thought of this. There does not seem to be direct way, but it is definetely possible. Worst case I can add the pdf links to toggle menu that is in the header in the UI. A more straightforward download button that is not hardcoded but is extensible might be possible in the UI too. I will look into that.

> Can you please an issue for cover image in this repository and assign it to me. I will discuss the problem with idta

Sure thing.

> I guess it is not a good idea to reference these links in Readme.md, as we will have to update it, if new docs appear

Yes it is a temporary solution. Linking anything that is generated content in the readme is not good, including the website sections themselves, as they are prone to change too. But as I said, this is just temporary for development purposes.
