### ISSUE TITLE
Formatting of notes

### ISSUE THREAD

**Issue by BirgitBoss** [rwth-iat/aas-specs-antora#13]
Notes marked with 

```
====
<note>
====
```

should be displayed in a box or some other way. Example:
Current state

![image](https://github.com/rwth-iat/aas-specs-antora/assets/59824205/8f238c9c-0196-4cb2-8a87-95eac1076e5f)

instead

![image](https://github.com/rwth-iat/aas-specs-antora/assets/59824205/d03e6a8d-59bd-4f89-91a1-6033d187a23d)

**Comment by monsieuremre** [comment]
We are using custom CSS styling for various elements in our UI to make the page appear as similar as can be to the original documentation source file. This is why, we explicitly format all such section, but especially the notes, to appear in a similar fashion to the original style. As such, these note boxes already exist, and they are formatted blue.

In any example page such as [this one](https://rwth-iat.github.io/aas-specs-antora/IDTA-01001/snapshot/IDTA-01001_General.html), you will be able to spot a few blue boxes easily.

The two examples of pictures provided do not seem to originate from the documentation website. Please specify where these images come from specifically and help us identify the issue, if we are missing a detail here.

**Comment by BirgitBoss** [comment]
I checked again, but notes do not have a blue box around, see https://rwth-iat.github.io/aas-specs-antora/IDTA-01001/snapshot/Spec/IDTA-01001_Metamodel_Common.html and search for "Note ". It is the same on the page you referenced: no box around notes.

You are right: the second figure is coming from another documentation configuration. But the first is from this configuration.

**Comment by monsieuremre** [comment]
I can see some problems, but this is not related to notes' formatting. All note blocks are formatted as such.

But I noticed that some parts of the text, that are clearly meant to be note blocks, are not note blocks, and not formatted as notes as a results. Theree is only a few of them, but they need fixing in the source file. I provide a screenshot with both examples. All note blocks are light blue boxes, those that aren't are not note blocks. In the source file, we need to add ==== note ==== around the note for it to be actually a note block.
![Screenshot from 2024-04-04 14-03-27](https://github.com/rwth-iat/aas-specs-antora/assets/130907164/c3358fbc-f80d-472e-a55b-60ff75019ddd)

**Comment by BirgitBoss** [comment]
Ah, ok. You might be right, I corrected a lot of notes in the past days but the PRs are not yet merged. Thank you!
