### ISSUE TITLE
Fix urls in `index.adoc`

### ISSUE THREAD

**Issue by zrgt** [rwth-iat/aas-specs-antora#7]
We should fix the links in table with docs images in `index.adoc`, as currently these are corrupted

**Comment by monsieuremre** [comment]
I don't understand. Which index.adoc is affected and which links are we talking about. Can you elaborate?

**Comment by zrgt** [comment]
Sorry, forgot to push the commits. As I understand correctly this repository is also used for the home page.

The home page is `index.adoc` here:
https://github.com/rwth-iat/aas-specs-antora/blob/main/modules/ROOT/pages/index.adoc

You will find links in the table in index.adoc

**Comment by zrgt** [comment]
Fixed with [25b4db2](https://github.com/rwth-iat/aas-specs-antora/commit/25b4db23418761be4b2724976889cf92a595cff8)
